### ISSUE TITLE
Trade Confirmations not Working

### ISSUE THREAD

**Issue by vale981** [Jessecar96/SteamDesktopAuthenticator#119]
Yo, there are some kind of problems with the trade confirmations (They are simply not showing anything).
Cheers ;D

**Comment by MetalRuller** [comment]
Yep, just tested it aswell.

**Comment by Toff-kun** [comment]
My trade confirmations stopped working as well. Might have something to do with me using the Deauthorize all other devices option on Steam.
Version 0.3.1 just shows a blank window with Refresh button that does nothing.
Version 0.2.3 crashes with the following error
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Steam_Desktop_Authenticator.ConfirmationForm.loadConfirmations(Boolean retry)
   at Steam_Desktop_Authenticator.ConfirmationForm..ctor(SteamGuardAccount account)
   at Steam_Desktop_Authenticator.MainForm.btnTradeConfirmations_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
