### ISSUE TITLE
Input user and pass, but doesn't log in and gives error?

### ISSUE THREAD

**Issue by volovikariel** [Jessecar96/SteamDesktopAuthenticator#142]
Error is 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Steam_Desktop_Authenticator.LoginForm.<RefreshLogin>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

It happens when I start it of, give it a user and pass, but it just isn't logged in, I expect it's because there isn't a mafile being created?? So when I try to log in again , error.

**Comment by volovikariel** [comment]
Turned it I had to restart it, it works now, there's a mafile, hooray :) great update
