### ISSUE TITLE
Unhandled exception when launching the application

### ISSUE THREAD

**Issue by Rakshaza** [Jessecar96/SteamDesktopAuthenticator#16]
The program works great on my desktop, but I can't seem to make it work on my laptop. I keep getting this as soon as i launch the application: http://i.imgur.com/RfTI2E1.jpg

**Comment by Top-Cat** [comment]
A quick trip to google suggests you're lacking the latest .NET framework (4.5)

**Comment by geel9** [comment]
Try installing .NET 4.5.2

**Comment by Rakshaza** [comment]
Thanks, it works now:>

**Comment by EvgenKo423** [comment]
Windows 7 x64. I am also getting an "Unhandled exception" when just launching an app:
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Steam_Desktop_Authenticator.MainForm.loadAccountsList()
   at Steam_Desktop_Authenticator.MainForm.MainForm_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```
I am having a .NET 4.0, but the error is not the same as Rakshaza's.
BTW, do you _really_ use something from the .NET 4.5?? If not you'd better use the lowest .NET version possible to not cause such problems to other people.
