### ISSUE TITLE
Unhandled Exception when checking trade confirmations (v 0.2.3)

### ISSUE THREAD

**Issue by zirune** [Jessecar96/SteamDesktopAuthenticator#19]
Using the latest version (0.2.3), an "Object reference not set to an instance of an object" error occurs when clicking on the "Trade Confirmations" button. I can't do anything with trade confirmations because of this.
    
```
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Steam_Desktop_Authenticator.ConfirmationForm.loadConfirmations(Boolean retry)
       at Steam_Desktop_Authenticator.ConfirmationForm..ctor(SteamGuardAccount account)
       at Steam_Desktop_Authenticator.MainForm.btnTradeConfirmations_Click(Object sender, EventArgs e)
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by ThePonyLuver** [comment]
I've had the same problem too. Don't know what causes it to do that.

**Comment by ThePonyLuver** [comment]
I get this text whenever I click on Trade Confirmations:
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at SteamAuth.SteamGuardAccount.FetchConfirmations()
   at Steam_Desktop_Authenticator.ConfirmationForm.loadConfirmations()
   at Steam_Desktop_Authenticator.ConfirmationForm..ctor(SteamGuardAccount account)
   at Steam_Desktop_Authenticator.MainForm.btnTradeConfirmations_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ItsHipsterNoah** [comment]
![capture](https://cloud.githubusercontent.com/assets/13893647/11604946/b41f424c-9aa8-11e5-9bc5-5e219c0b93f9.JPG)

I've been experiencing the same problem as well.

**Comment by lavaraba** [comment]
I don't get this message.. but I simply get 'Unable to accept confirmation', might be the same problem.

**Comment by zirune** [comment]
For whatever reason, it's working today. I haven't done anything differently (as far as I know), but I just managed to accept a trade offer...

**Comment by Top-Cat** [comment]
This thread is 3 issues....

**Comment by Jessecar96** [comment]
The exceptions when loading confirmations should be fixed as of the latest commits.
(Not released as of yet)
