### ISSUE TITLE
Crash on 503 error when verifying email code

### ISSUE THREAD

**Issue by srabouin** [Jessecar96/SteamDesktopAuthenticator#2]
Opened the app, put my username + password, received email code, put in the email code, crash:

************** Exception Text **************
System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at SteamAuth.SteamWeb.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers, String referer)
   at SteamAuth.UserLogin.DoLogin()
   at Steam_Desktop_Authenticator.LoginForm.btnSteamLogin_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at System.Windows.Forms.Form.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.TextBoxBase.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

**Comment by geel9** [comment]
Should be fixed in f97c93685ea7b435c326d71bb1693a592b7ae43f
