### ISSUE TITLE
Checking confirmations on linux while using mono results in crash

### ISSUE THREAD

**Issue by SierraNB** [Jessecar96/SteamDesktopAuthenticator#736]
Version: 1.0.10
Mono version 6.12.0.122
OS version: Ubuntu 20.04.3 LTS x86x64
Computer specs: i5-7600k @4ghz, GTX 1070, 32gb DDR4 RAM

Issue: After running the complied .exe with the mono runtime,  attempting to check the confirmations on my account, the program crashes after clicking confirmations. 

Steps to recreation: Click on "view confirmations" 

Crash logs:

> 
> =================================================================
>         Native Crash Reporting
> =================================================================
> Got a SIGABRT while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries 
> used by your application.
> =================================================================
> 
> =================================================================
>         Native stacktrace:
> =================================================================
>         0x5588cf82fc4b - /usr/bin/mono : 
>         0x5588cf82ffdd - /usr/bin/mono : 
>         0x5588cf7dce47 - /usr/bin/mono : 
>         0x5588cf82f1cc - /usr/bin/mono : 
>         0x7f71597a93c0 - /lib/x86_64-linux-gnu/libpthread.so.0 : 
>         0x7f715929a18b - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
>         0x7f7159279859 - /lib/x86_64-linux-gnu/libc.so.6 : abort
>         0x5588cf79f3c4 - /usr/bin/mono : 
>         0x5588cfa83715 - /usr/bin/mono : 
>         0x5588cfaa0b8e - /usr/bin/mono : 
>         0x5588cfaa1243 - /usr/bin/mono : monoeg_assertion_message
>         0x5588cfaa12bd - /usr/bin/mono : 
>         0x5588cf98a874 - /usr/bin/mono : 
>         0x5588cf98eba6 - /usr/bin/mono : 
>         0x5588cf929a35 - /usr/bin/mono : 
>         0x5588cf9b5126 - /usr/bin/mono : 
>         0x5588cf86e7e7 - /usr/bin/mono : 
>         0x5588cf83432f - /usr/bin/mono : 
>         0x5588cf836766 - /usr/bin/mono : 
>         0x5588cf7a8132 - /usr/bin/mono : 
>         0x5588cf7e0786 - /usr/bin/mono : 
>         0x5588cf7e1284 - /usr/bin/mono : 
>         0x40e2b393 - Unknown
> 
> =================================================================
>         Telemetry Dumper:
> =================================================================
> Pkilling 0x140124634572544x from 0x140124803641280x
> Pkilling 0x140124630370048x from 0x140124803641280x
> Pkilling 0x140124626167552x from 0x140124803641280x
> Pkilling 0x140124618176256x from 0x140124803641280x
> Pkilling 0x140124612400896x from 0x140124803641280x
> Pkilling 0x140124599875328x from 0x140124803641280x
> Pkilling 0x140124632471296x from 0x140124803641280x
> Pkilling 0x140124628268800x from 0x140124803641280x
> Pkilling 0x140124624066304x from 0x140124803641280x
> Pkilling 0x140124753835776x from 0x140124803641280x
> Pkilling 0x140124608263936x from 0x140124803641280x
> Pkilling 0x140124614502144x from 0x140124803641280x
> Entering thread summarizer pause from 0x140124803641280x
> Finished thread summarizer pause from 0x140124803641280x.
> Failed to create breadcrumb file (null)/crash_hash_0xfc5e2f28c
> 
> Waiting for dumping threads to resume
> 
> =================================================================
>         External Debugger Dump:
> =================================================================
> [New LWP 44373]
> [New LWP 44374]
> [New LWP 44380]
> [New LWP 44381]
> [New LWP 44382]
> [New LWP 44383]
> [New LWP 44384]
> [New LWP 44385]
> [New LWP 44386]
> [New LWP 44387]
> [New LWP 44395]
> [New LWP 44428]
> [New LWP 44696]
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> 0x00007f7159339dff in __GI___wait4 (pid=44700, stat_loc=0x7fff998d2e14, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
> 27      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
>   Id   Target Id                                           Frame 
> * 1    Thread 0x7f7159252fc0 (LWP 44371) "mono"            0x00007f7159339dff in __GI___wait4 (pid=44700, stat_loc=0x7fff998d2e14, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
>   2    Thread 0x7f71587ff700 (LWP 44373) "SGen worker"     futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5588cfc181e8) at ../sysdeps/nptl/futex-internal.h:183
>   3    Thread 0x7f71562d3700 (LWP 44374) "Finalizer"       futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5588cfc094a0) at ../sysdeps/nptl/futex-internal.h:320
>   4    Thread 0x7f714ef15700 (LWP 44380) "Thread Pool Wor" 0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714ef14d50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
>   5    Thread 0x7f714ed14700 (LWP 44381) "Thread Pool Wor" 0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714ed13d50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
>   6    Thread 0x7f714eb13700 (LWP 44382) "Thread Pool Wor" 0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714eb12d50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
>   7    Thread 0x7f714e912700 (LWP 44383) "Thread Pool Wor" 0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714e911d50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
>   8    Thread 0x7f714e711700 (LWP 44384) "Timer-Scheduler" futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f714e710020, clockid=<optimized out>, expected=0, futex_word=0x5588cff0ca98) at ../sysdeps/nptl/futex-internal.h:320
>   9    Thread 0x7f714e173700 (LWP 44385) "Thread Pool I/O" 0x00007f7159369aff in __GI___poll (fds=0x7f7140062d70, nfds=5, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
>   10   Thread 0x7f714ddf2700 (LWP 44386) "Thread Pool Wor" __lll_lock_wait (futex=futex@entry=0x5588cfd9c190, private=0) at lowlevellock.c:52
>   11   Thread 0x7f714dbf1700 (LWP 44387) "Thread Pool Wor" 0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714dbf0d50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
>   12   Thread 0x7f714d7ff700 (LWP 44395) "Thread Pool Wor" 0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714d7fed50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
>   13   Thread 0x7f714cfff700 (LWP 44428) "Thread Pool Wor" 0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714cffed50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
>   14   Thread 0x7f714f116700 (LWP 44696) "mono"            futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f714f115ca0, clockid=<optimized out>, expected=0, futex_word=0x5588cfc18888) at ../sysdeps/nptl/futex-internal.h:320
> 
> Thread 14 (Thread 0x7f714f116700 (LWP 44696)):
> #0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f714f115ca0, clockid=<optimized out>, expected=0, futex_word=0x5588cfc18888) at ../sysdeps/nptl/futex-internal.h:320
> #1  __pthread_cond_wait_common (abstime=0x7f714f115ca0, clockid=<optimized out>, mutex=0x5588cfc188a0, cond=0x5588cfc18860) at pthread_cond_wait.c:520
> #2  __pthread_cond_timedwait (cond=0x5588cfc18860, mutex=0x5588cfc188a0, abstime=0x7f714f115ca0) at pthread_cond_wait.c:656
> #3  0x00005588cfa88a0e in  ()
> #4  0x00005588cfa937d9 in  ()
> #5  0x00005588cfa2df53 in  ()
> #6  0x00005588cf9daafa in  ()
> #7  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #8  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 13 (Thread 0x7f714cfff700 (LWP 44428)):
> #0  0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714cffed50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
> #1  do_futex_wait (sem=sem@entry=0x5588cfc09d88, abstime=abstime@entry=0x7f714cffed50, clockid=0) at sem_waitcommon.c:112
> #2  0x00007f71597a7743 in __new_sem_wait_slow (sem=0x5588cfc09d88, abstime=0x7f714cffed50, clockid=0) at sem_waitcommon.c:184
> #3  0x00005588cfa2d2b8 in  ()
> #4  0x00005588cf9daafa in  ()
> #5  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #6  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 12 (Thread 0x7f714d7ff700 (LWP 44395)):
> #0  0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714d7fed50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
> #1  do_futex_wait (sem=sem@entry=0x5588cfc09d88, abstime=abstime@entry=0x7f714d7fed50, clockid=0) at sem_waitcommon.c:112
> #2  0x00007f71597a7743 in __new_sem_wait_slow (sem=0x5588cfc09d88, abstime=0x7f714d7fed50, clockid=0) at sem_waitcommon.c:184
> #3  0x00005588cfa2d2b8 in  ()
> #4  0x00005588cf9daafa in  ()
> #5  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #6  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 11 (Thread 0x7f714dbf1700 (LWP 44387)):
> #0  0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714dbf0d50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
> #1  do_futex_wait (sem=sem@entry=0x5588cfc09d88, abstime=abstime@entry=0x7f714dbf0d50, clockid=0) at sem_waitcommon.c:112
> #2  0x00007f71597a7743 in __new_sem_wait_slow (sem=0x5588cfc09d88, abstime=0x7f714dbf0d50, clockid=0) at sem_waitcommon.c:184
> #3  0x00005588cfa2d2b8 in  ()
> #4  0x00005588cf9daafa in  ()
> #5  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #6  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 10 (Thread 0x7f714ddf2700 (LWP 44386)):
> #0  __lll_lock_wait (futex=futex@entry=0x5588cfd9c190, private=0) at lowlevellock.c:52
> #1  0x00007f71597a0131 in __GI___pthread_mutex_lock (mutex=0x5588cfd9c190) at ../nptl/pthread_mutex_lock.c:115
> #2  0x00005588cf913bb6 in mono_domain_lock ()
> #3  0x00005588cf8387d4 in  ()
> #4  0x00005588cf838915 in  ()
> #5  0x00005588cf7da8f2 in  ()
> #6  0x0000000040b9357d in  ()
> #7  0x0000000000000000 in  ()
> 
> Thread 9 (Thread 0x7f714e173700 (LWP 44385)):
> #0  0x00007f7159369aff in __GI___poll (fds=0x7f7140062d70, nfds=5, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
> #1  0x00005588cf9de309 in  ()
> #2  0x00005588cf9df6bb in  ()
> #3  0x00005588cf9daafa in  ()
> #4  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #5  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 8 (Thread 0x7f714e711700 (LWP 44384)):
> #0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f714e710020, clockid=<optimized out>, expected=0, futex_word=0x5588cff0ca98) at ../sysdeps/nptl/futex-internal.h:320
> #1  __pthread_cond_wait_common (abstime=0x7f714e710020, clockid=<optimized out>, mutex=0x5588cff0ca48, cond=0x5588cff0ca70) at pthread_cond_wait.c:520
> #2  __pthread_cond_timedwait (cond=0x5588cff0ca70, mutex=0x5588cff0ca48, abstime=0x7f714e710020) at pthread_cond_wait.c:656
> #3  0x00005588cfa88a0e in  ()
> #4  0x00005588cf9e5c7a in  ()
> #5  0x00005588cf9e72eb in  ()
> #6  0x00005588cf9e7b10 in  ()
> #7  0x00005588cf9d7f9a in  ()
> #8  0x00005588cf96c9a6 in  ()
> #9  0x00000000408cd222 in  ()
> #10 0x00007f7158baf200 in  ()
> #11 0x00007f7158baf2f8 in  ()
> #12 0x00007f7158baf130 in  ()
> #13 0x0000000000000000 in  ()
> 
> Thread 7 (Thread 0x7f714e912700 (LWP 44383)):
> #0  0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714e911d50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
> #1  do_futex_wait (sem=sem@entry=0x5588cfc09d88, abstime=abstime@entry=0x7f714e911d50, clockid=0) at sem_waitcommon.c:112
> #2  0x00007f71597a7743 in __new_sem_wait_slow (sem=0x5588cfc09d88, abstime=0x7f714e911d50, clockid=0) at sem_waitcommon.c:184
> #3  0x00005588cfa2d2b8 in  ()
> #4  0x00005588cf9daafa in  ()
> #5  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #6  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 6 (Thread 0x7f714eb13700 (LWP 44382)):
> #0  0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714eb12d50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
> #1  do_futex_wait (sem=sem@entry=0x5588cfc09d88, abstime=abstime@entry=0x7f714eb12d50, clockid=0) at sem_waitcommon.c:112
> #2  0x00007f71597a7743 in __new_sem_wait_slow (sem=0x5588cfc09d88, abstime=0x7f714eb12d50, clockid=0) at sem_waitcommon.c:184
> #3  0x00005588cfa2d2b8 in  ()
> #4  0x00005588cf9daafa in  ()
> #5  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #6  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 5 (Thread 0x7f714ed14700 (LWP 44381)):
> #0  0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714ed13d50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
> #1  do_futex_wait (sem=sem@entry=0x5588cfc09d88, abstime=abstime@entry=0x7f714ed13d50, clockid=0) at sem_waitcommon.c:112
> #2  0x00007f71597a7743 in __new_sem_wait_slow (sem=0x5588cfc09d88, abstime=0x7f714ed13d50, clockid=0) at sem_waitcommon.c:184
> #3  0x00005588cfa2d2b8 in  ()
> #4  0x00005588cf9daafa in  ()
> #5  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #6  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 4 (Thread 0x7f714ef15700 (LWP 44380)):
> #0  0x00007f71597a7618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7f714ef14d50, clockid=0, expected=0, futex_word=0x5588cfc09d88) at ../sysdeps/nptl/futex-internal.h:320
> #1  do_futex_wait (sem=sem@entry=0x5588cfc09d88, abstime=abstime@entry=0x7f714ef14d50, clockid=0) at sem_waitcommon.c:112
> #2  0x00007f71597a7743 in __new_sem_wait_slow (sem=0x5588cfc09d88, abstime=0x7f714ef14d50, clockid=0) at sem_waitcommon.c:184
> #3  0x00005588cfa2d2b8 in  ()
> #4  0x00005588cf9daafa in  ()
> #5  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #6  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 3 (Thread 0x7f71562d3700 (LWP 44374)):
> #0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5588cfc094a0) at ../sysdeps/nptl/futex-internal.h:320
> #1  do_futex_wait (sem=sem@entry=0x5588cfc094a0, abstime=0x0, clockid=0) at sem_waitcommon.c:112
> #2  0x00007f71597a74e8 in __new_sem_wait_slow (sem=0x5588cfc094a0, abstime=0x0, clockid=0) at sem_waitcommon.c:184
> #3  0x00005588cfa1d078 in  ()
> #4  0x00005588cf9daafa in  ()
> #5  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #6  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 2 (Thread 0x7f71587ff700 (LWP 44373)):
> #0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5588cfc181e8) at ../sysdeps/nptl/futex-internal.h:183
> #1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5588cfc18200, cond=0x5588cfc181c0) at pthread_cond_wait.c:508
> #2  __pthread_cond_wait (cond=0x5588cfc181c0, mutex=0x5588cfc18200) at pthread_cond_wait.c:638
> #3  0x00005588cfa7b276 in  ()
> #4  0x00007f715979d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #5  0x00007f7159376293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 1 (Thread 0x7f7159252fc0 (LWP 44371)):
> #0  0x00007f7159339dff in __GI___wait4 (pid=44700, stat_loc=0x7fff998d2e14, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
> #1  0x00005588cf82fec2 in  ()
> #2  0x00005588cf82ffdd in  ()
> #3  0x00005588cf7dce47 in  ()
> #4  0x00005588cf82f1cc in  ()
> #5  0x00007f71597a93c0 in <signal handler called> () at /lib/x86_64-linux-gnu/libpthread.so.0
> #6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
> #7  0x00007f7159279859 in __GI_abort () at abort.c:79
> #8  0x00005588cf79f3c4 in  ()
> #9  0x00005588cfa83715 in  ()
> #10 0x00005588cfaa0b8e in  ()
> #11 0x00005588cfaa1243 in monoeg_assertion_message ()
> #12 0x00005588cfaa12bd in  ()
> #13 0x00005588cf98a874 in  ()
> #14 0x00005588cf98eba6 in  ()
> #15 0x00005588cf929a35 in  ()
> #16 0x00005588cf9b5126 in  ()
> #17 0x00005588cf86e7e7 in  ()
> #18 0x00005588cf83432f in  ()
> #19 0x00005588cf836766 in  ()
> #20 0x00005588cf7a8132 in  ()
> #21 0x00005588cf7e0786 in  ()
> #22 0x00005588cf7e1284 in  ()
> #23 0x0000000040e2b393 in  ()
> #24 0x00007fff998d673d in  ()
> #25 0x0000000040e2b3c1 in  ()
> #26 0x00007fff998d5330 in  ()
> #27 0x00007fff998d5168 in  ()
> #28 0x00005588cfdc6220 in  ()
> #29 0x00005588cfc1a220 in  ()
> #30 0x00007f71589a0478 in  ()
> #31 0x00000000000002c4 in  ()
> #32 0x00005588cfde4d48 in  ()
> #33 0x00007fff998d5330 in  ()
> #34 0x00007fff998d5550 in  ()
> #35 0x00005588d0f1f608 in  ()
> #36 0x00007f71589a0478 in  ()
> #37 0x0000000000000330 in  ()
> #38 0x000000000000000c in  ()
> #39 0x000000000000002f in  ()
> #40 0x00005588cf9d3e6c in  ()
> #41 0x00007f714e211130 in  ()
> #42 0x0000000040bec75c in  ()
> #43 0x3ff0000000000000 in  ()
> #44 0x0000000000000000 in  ()
> [Inferior 1 (process 44371) detached]
> 
> =================================================================
>         Basic Fault Address Reporting
> =================================================================
> Memory around native instruction pointer (0x7f715929a18b):0x7f715929a17b  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
> 0x7f715929a18b  48 8b 84 24 08 01 00 00 64 48 33 04 25 28 00 00  H..$....dH3.%(..
> 0x7f715929a19b  00 75 26 44 89 c0 48 81 c4 18 01 00 00 c3 0f 1f  .u&D..H.........
> 0x7f715929a1ab  80 00 00 00 00 48 8b 15 b9 4c 1a 00 f7 d8 41 b8  .....H...L....A.
> 
> =================================================================
>         Managed Stacktrace:
> =================================================================
>           at <unknown> <0xffffffff>
>           at CefSharp.WinForms.CefSettings:.ctor <0x0002b>
>           at Steam_Desktop_Authenticator.ConfirmationFormWeb:.ctor <0x000cb>
>           at Steam_Desktop_Authenticator.ConfirmationFormWeb:.ctor <0x0005b>
>           at <btnTradeConfirmations_Click>d__19:MoveNext <0x00603>
>           at MoveNextRunner:InvokeMoveNext <0x000b0>
>           at System.Threading.ExecutionContext:RunInternal <0x001a7>
>           at System.Threading.ExecutionContext:Run <0x00042>
>           at MoveNextRunner:Run <0x000b9>
>           at System.Threading.Tasks.AwaitTaskContinuation:InvokeAction <0x00048>
>           at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0006d>
>           at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x0010a>
>           at System.Threading.Tasks.Task:FinishContinuations <0x0027e>
>           at System.Threading.Tasks.Task:FinishStageThree <0x00080>
>           at System.Threading.Tasks.Task`1:TrySetResult <0x000da>
>           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x0010a>
>           at <RefreshAccountSession>d__42:MoveNext <0x00602>
>           at MoveNextRunner:InvokeMoveNext <0x000b0>
>           at System.Threading.ExecutionContext:RunInternal <0x001a7>
>           at System.Threading.ExecutionContext:Run <0x00042>
>           at MoveNextRunner:Run <0x000b9>
>           at System.Threading.Tasks.AwaitTaskContinuation:InvokeAction <0x00048>
>           at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0006d>
>           at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x0010a>
>           at System.Threading.Tasks.Task:FinishContinuations <0x0027e>
>           at System.Threading.Tasks.Task:FinishStageThree <0x00080>
>           at System.Threading.Tasks.Task`1:TrySetResult <0x000da>
>           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x0010a>
>           at <RefreshSessionAsync>d__65:MoveNext <0x005b2>
>           at MoveNextRunner:InvokeMoveNext <0x000b0>
>           at System.Threading.ExecutionContext:RunInternal <0x001a7>
>           at System.Threading.ExecutionContext:Run <0x00042>
>           at MoveNextRunner:Run <0x000b9>
>           at System.Threading.Tasks.AwaitTaskContinuation:InvokeAction <0x00048>
>           at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0006d>
>           at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x0010a>
>           at System.Threading.Tasks.Task:FinishContinuations <0x0027e>
>           at System.Threading.Tasks.Task:FinishStageThree <0x00080>
>           at System.Threading.Tasks.Task`1:TrySetResult <0x000e5>
>           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000d2>
>           at <RequestAsync>d__3:MoveNext <0x00ed2>
>           at MoveNextRunner:InvokeMoveNext <0x000b0>
>           at System.Threading.ExecutionContext:RunInternal <0x001a7>
>           at System.Threading.ExecutionContext:Run <0x00042>
>           at MoveNextRunner:Run <0x000b9>
>           at <>c:<.cctor>b__7_0 <0x00048>
>           at <Module>:runtime_invoke_void__this___object <0x0009c>
>           at <unknown> <0xffffffff>
>           at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x000ad>
>           at System.Reflection.RuntimeMethodInfo:Invoke <0x00114>
>           at System.Reflection.MethodBase:Invoke <0x00047>
>           at System.Delegate:DynamicInvokeImpl <0x00296>
>           at System.MulticastDelegate:DynamicInvokeImpl <0x00049>
>           at System.Delegate:DynamicInvoke <0x00036>
>           at System.Windows.Forms.XplatUIDriverSupport:ExecutionCallback <0x0005a>
>           at System.Windows.Forms.XplatUIDriverSupport:ExecutionCallbackInContext <0x000ab>
>           at System.Threading.ExecutionContext:RunInternal <0x001a7>
>           at System.Threading.ExecutionContext:Run <0x00042>
>           at System.Threading.ExecutionContext:Run <0x00067>
>           at System.Windows.Forms.XplatUIDriverSupport:ExecuteClientMessage <0x00162>
>           at System.Windows.Forms.XplatUIX11:GetMessage <0x04597>
>           at System.Windows.Forms.XplatUI:GetMessage <0x00064>
>           at System.Windows.Forms.Application:RunLoop <0x00acb>
>           at System.Windows.Forms.Application:Run <0x0007f>
>           at System.Windows.Forms.Application:Run <0x0004f>
>           at Steam_Desktop_Authenticator.Program:Main <0x003db>
>           at <Module>:runtime_invoke_void_object <0x00091>
> =================================================================
> 
> 
>

**Comment by nolddor** [comment]
@Jessecar96 any hints about this? Getting the same error on Debian.
